(()=>{
const A=window.APP;
const adminView=document.getElementById('adminView');
adminView?.classList.add('hidden');

const style=document.createElement('style');
style.textContent=`
.admin-auth-gate{min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at top right,#172750 0,#0b1739 38%,#071027 100%);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial;color:#0c1d4a}.admin-auth-card{width:min(430px,100%);background:#fff;border-radius:26px;padding:30px;box-shadow:0 28px 70px rgba(0,0,0,.32)}.admin-auth-brand{display:flex;align-items:center;gap:12px;margin-bottom:24px}.admin-auth-logo{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:#a60f17;color:#fff;font-weight:950;font-size:21px}.admin-auth-brand strong{display:block;font-size:20px}.admin-auth-brand span{display:block;color:#77809a;font-size:12px;margin-top:2px}.admin-auth-card h1{font-size:27px;margin:0 0 7px}.admin-auth-card>p{color:#77809a;font-size:13px;line-height:1.55;margin:0 0 21px}.admin-auth-field{display:flex;flex-direction:column;gap:7px;margin-top:12px}.admin-auth-field label{font-size:12px;font-weight:900;color:#4e5872}.admin-auth-field input{width:100%;border:1px solid #dfe3ed;border-radius:13px;padding:13px 14px;outline:none;background:#fff}.admin-auth-field input:focus{border-color:#a60f17;box-shadow:0 0 0 3px rgba(166,15,23,.09)}.admin-auth-actions{display:grid;gap:9px;margin-top:19px}.admin-auth-actions button{border:0;border-radius:13px;padding:13px;font-weight:900;cursor:pointer}.admin-auth-login{background:#a60f17;color:#fff}.admin-auth-actions button:disabled{opacity:.55;cursor:wait}.admin-auth-message{min-height:20px;margin-top:13px;font-size:12px;line-height:1.45;color:#77809a}.admin-auth-message.error{color:#b91c1c}.admin-auth-note{margin-top:18px;padding-top:16px;border-top:1px solid #eef0f5;color:#8a92a6;font-size:11px;line-height:1.5}.admin-logout{margin-top:7px;border:0;background:#eef1f6;color:#0c1d4a;border-radius:9px;padding:7px 10px;font-size:11px;font-weight:900;cursor:pointer}
`;
document.head.appendChild(style);

const gate=document.createElement('div');
gate.className='admin-auth-gate';
gate.innerHTML=`<div class="admin-auth-card"><div class="admin-auth-brand"><div class="admin-auth-logo">CP</div><div><strong>Comanda Prime</strong><span>Área administrativa protegida</span></div></div><h1>Acesso do administrador</h1><p>Entre com o usuário e a senha do administrador.</p><form id="adminAuthForm"><div class="admin-auth-field"><label>Usuário</label><input id="adminAuthUser" type="text" autocomplete="username" required placeholder="Usuário"></div><div class="admin-auth-field"><label>Senha</label><input id="adminAuthPassword" type="password" inputmode="numeric" autocomplete="current-password" required placeholder="Senha"></div><div class="admin-auth-actions"><button class="admin-auth-login" id="adminLoginBtn" type="submit">Entrar</button></div></form><div id="adminAuthMessage" class="admin-auth-message">Digite o usuário e a senha.</div><div class="admin-auth-note">Acesso simples e separado do painel dos garçons.</div></div>`;
document.body.prepend(gate);

const $=id=>document.getElementById(id);let loadingAdmin=false;
function message(text,type=''){const e=$('adminAuthMessage');e.textContent=text;e.className='admin-auth-message '+type}
function busy(on){$('adminLoginBtn').disabled=on;$('adminLoginBtn').textContent=on?'Entrando...':'Entrar'}
function loadAdmin(user){if(loadingAdmin)return;loadingAdmin=true;gate.remove();adminView?.classList.remove('hidden');document.body.classList.add('admin-ready');const userBox=document.querySelector('.admin-user');if(userBox){const label=userBox.querySelector('span');if(label)label.textContent=user?.username||'Administrador';const out=document.createElement('button');out.className='admin-logout';out.textContent='Sair';out.onclick=async()=>{await A.adminLogout();location.reload()};userBox.appendChild(out)}const script=document.createElement('script');script.src='/admin.js?v=10';script.onload=()=>{const patch=document.createElement('script');patch.src='/admin-patch.js?v=10';document.body.appendChild(patch)};document.body.appendChild(script)}
async function authorizeExisting(){const access=await A.adminSession();if(access.ok)loadAdmin(access.user)}
async function enter(){const username=$('adminAuthUser').value.trim(),password=$('adminAuthPassword').value;if(!username||!password)return message('Informe usuário e senha.','error');busy(true);message('Validando acesso...');const login=await A.adminLogin(username,password);if(login.ok)return loadAdmin(login.user);busy(false);message('Usuário ou senha incorretos.','error')}
$('adminAuthForm').addEventListener('submit',e=>{e.preventDefault();enter()});
authorizeExisting();
})();