(()=>{
const SUPABASE_URL='https://dsipffnmerbowaddbcxe.supabase.co';
const SUPABASE_KEY='sb_publishable_vI64CItP0mGD4HD2DFJ2zw_zyZaveCz';
const STORAGE_KEY='comandaPrimeStateV5';
const cloud=(location.protocol==='http:'||location.protocol==='https:')&&!!window.supabase;
const db=cloud?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
const icons={Cervejas:'🍺',Bebidas:'🥤',Espetinhos:'🍢','Porções':'🍟',Drinks:'🍹'};
const seed={products:[{id:1,name:'Heineken 330ml',cat:'Cervejas',price:12,stock:84,min:20,active:true,emoji:'🍺',photo:''},{id:2,name:'Brahma Duplo Malte',cat:'Cervejas',price:9,stock:52,min:20,active:true,emoji:'🍺',photo:''},{id:3,name:'Coca-Cola lata',cat:'Bebidas',price:7,stock:31,min:12,active:true,emoji:'🥤',photo:''},{id:4,name:'Espetinho bovino',cat:'Espetinhos',price:12,stock:63,min:20,active:true,emoji:'🍢',photo:''},{id:5,name:'Caipirinha',cat:'Drinks',price:18,stock:22,min:8,active:true,emoji:'🍹',photo:''}],tables:Array.from({length:14},(_,i)=>({id:i+1,type:'mesa',client:'',status:'free',opened:0,total:0,items:[],waiter:'Garçom 01'})),tabs:[],closedSales:[],categories:['Cervejas','Bebidas','Espetinhos','Porções','Drinks'],employees:[{id:1,name:'Garçom 01',role:'Garçom',active:true},{id:2,name:'Administrador',role:'Administrador',active:true}],settings:{businessName:'Comanda Prime',waiterName:'Garçom 01',footer:'Atendimento rápido e simples'},updatedAt:Date.now()};
let state=clone(seed),version=1,rt=null;
const bc=('BroadcastChannel'in window&&!cloud)?new BroadcastChannel('comanda-prime-live-v5'):null;
function clone(v){return JSON.parse(JSON.stringify(v))}
function norm(s){s=s&&typeof s==='object'?s:clone(seed);s.products=Array.isArray(s.products)?s.products:clone(seed.products);s.tables=Array.isArray(s.tables)?s.tables:clone(seed.tables);s.tabs=Array.isArray(s.tabs)?s.tabs:[];s.closedSales=Array.isArray(s.closedSales)?s.closedSales:[];const derived=[...new Set(s.products.map(p=>p.cat).filter(Boolean))];s.categories=Array.isArray(s.categories)&&s.categories.length?[...new Set([...s.categories,...derived])]:derived;s.employees=Array.isArray(s.employees)&&s.employees.length?s.employees:clone(seed.employees);s.settings=Object.assign({},seed.settings,s.settings||{});s.tables.forEach(t=>{t.type='mesa';t.items=Array.isArray(t.items)?t.items:[];t.status=t.status||'free';t.waiter=t.waiter||s.settings.waiterName});s.tabs.forEach(t=>{t.type='comanda';t.items=Array.isArray(t.items)?t.items:[];t.status=t.status||'busy';t.waiter=t.waiter||s.settings.waiterName});return s}
function brl(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[s]))}
function toast(msg){const e=document.getElementById('toast');if(!e)return;e.textContent=msg;e.classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.add('hidden'),2400)}
function product(id){return state.products.find(p=>p.id===Number(id))}
function media(p){return p.photo?`<img src="${p.photo}" alt="${esc(p.name)}">`:(p.emoji||icons[p.cat]||'📦')}
function qty(t){return(t.items||[]).reduce((a,i)=>a+Number(i.qty||0),0)}
function openOrders(){return[...state.tables,...state.tabs].filter(t=>t.status!=='free')}
function today(ts=Date.now()){const d=new Date(ts);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function apply(next,v=null){if(!next?.products||!next?.tables)return;state=norm(next);if(v!==null)version=Number(v)||version;persist();window.renderPage?.()}
async function cloudCommit(mutator){for(let i=0;i<4;i++){const c=norm(clone(state));mutator(c);c.updatedAt=Date.now();const{data,error}=await db.rpc('update_app_state',{p_expected_version:version,p_data:c});if(error)throw error;const r=Array.isArray(data)?data[0]:data;if(r?.success){state=norm(c);version=Number(r.new_version)||version;persist();window.renderPage?.();return true}if(r?.current_data){state=norm(r.current_data);version=Number(r.new_version)||version;persist();window.renderPage?.()}}throw new Error('Conflito')}
async function commit(mutator,msg){try{if(cloud)await cloudCommit(mutator);else{mutator(state);state=norm(state);state.updatedAt=Date.now();persist();bc?.postMessage(state);window.renderPage?.()}if(msg)toast(msg);return true}catch(e){console.error(e);toast('Não foi possível salvar. Verifique a conexão.');return false}}
async function init(){if(cloud){try{const{data,error}=await db.from('app_state').select('data,version').eq('id',1).single();if(error)throw error;if(data?.data)apply(data.data,data.version);rt=db.channel('comanda-prime-v5').on('postgres_changes',{event:'UPDATE',schema:'public',table:'app_state',filter:'id=eq.1'},p=>p.new?.data&&apply(p.new.data,p.new.version)).subscribe()}catch(e){console.error(e);try{state=norm(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch(_){state=norm(clone(seed))}toast('Sem conexão com o servidor. Exibindo dados locais.')}}else{try{state=norm(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch(_){state=norm(clone(seed))}bc&&(bc.onmessage=e=>apply(e.data));window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&e.newValue)try{apply(JSON.parse(e.newValue))}catch(_){}})}window.renderPage?.();const live=cloud?'Supabase • tempo real online':'Modo local';document.querySelectorAll('[data-live]').forEach(e=>e.textContent=live);if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/sw.js').catch(()=>{})}
window.APP={state:()=>state,commit,init,brl,esc,product,media,qty,openOrders,today,icons,toast,clone};
})();
