(()=>{
const A=window.APP,$=id=>document.getElementById(id);
let current=null,cart={},cat='',individual=false,mode='all',saving=false;
const currentWaiter=()=>A.waiterUser()?.displayName||A.state().settings.waiterName||'Garçom';
const currentUsername=()=>A.waiterUser()?.username||'';
const SUPABASE_URL='https://dsipffnmerbowaddbcxe.supabase.co';
const SUPABASE_KEY='sb_publishable_vI64CItP0mGD4HD2DFJ2zw_zyZaveCz';
const WAITER_SESSION_KEY='comandaPrimeWaiterSessionV1';
const PENDING_LAUNCH_KEY='comandaPrimePendingLaunchV1';

const editStyle=document.createElement('style');
editStyle.textContent=`
.cart-existing-title{margin:10px 0 6px;font-size:11px;font-weight:950;color:#626c82;text-transform:uppercase;letter-spacing:.04em}.cart-line.existing{align-items:flex-start}.cart-line-main{display:flex;flex-direction:column;gap:2px;min-width:0}.cart-line-main small{font-size:10px;color:#8a92a6}.cart-actions.editing{flex-wrap:wrap;justify-content:flex-end}.cart-actions.editing button{width:auto!important;min-width:34px;padding:6px 8px;font-size:10px}.cart-actions .swap-item{background:#e8f0ff!important;color:#173e86!important}.cart-actions .remove-item{background:#feecec!important;color:#a60f17!important}
#deleteOrder{background:#fff0f0!important;color:#a60f17!important;border:1px solid #f2b8b8!important;font-weight:900!important}
#deleteOrder:disabled,#confirmOrder:disabled,#requestClose:disabled{opacity:.6!important;pointer-events:none!important}
`;
document.head.appendChild(editStyle);

function waiterToken(){try{return JSON.parse(localStorage.getItem(WAITER_SESSION_KEY)||'null')?.token||''}catch(_){return''}}
function rpcRow(data){return Array.isArray(data)?data[0]:data}
async function waiterRpc(name,body,timeout=15000){
  const token=waiterToken();
  if(!token)throw new Error('Sessão do garçom inválida');
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
  try{
    const res=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({p_session_token:token,...body}),signal:controller.signal,cache:'no-store'});
    const data=await res.json().catch(()=>null),row=rpcRow(data);
    if(!res.ok)throw new Error(row?.message||row?.error||`Erro ${res.status}`);
    return row||{};
  }finally{clearTimeout(timer)}
}
function applyStocks(updates){const s=A.state();(updates||[]).forEach(u=>{const p=s.products.find(x=>Number(x.id)===Number(u.pid));if(p)p.stock=Number(u.stock)})}
function applyOrder(orderType,orderId,orderData){const s=A.state();if(!orderData)return;if(orderType==='mesa'){const i=s.tables.findIndex(x=>Number(x.id)===Number(orderId));if(i>=0)s.tables[i]=orderData}else{const i=s.tabs.findIndex(x=>Number(x.id)===Number(orderId));if(i>=0)s.tabs[i]=orderData;else s.tabs.push(orderData)}}
function makeRequestId(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2,12)}`}
function pendingLaunchId(key){try{const p=JSON.parse(sessionStorage.getItem(PENDING_LAUNCH_KEY)||'null');if(p?.key===key&&p?.id)return p.id;const id=makeRequestId();sessionStorage.setItem(PENDING_LAUNCH_KEY,JSON.stringify({key,id,at:Date.now()}));return id}catch(_){return makeRequestId()}}
function clearPendingLaunch(){try{sessionStorage.removeItem(PENDING_LAUNCH_KEY)}catch(_){}}
function setBusy(button,busy,label){if(!button)return;button.disabled=busy;if(busy){button.dataset.oldText=button.textContent;button.textContent=label}else if(button.dataset.oldText){button.textContent=button.dataset.oldText;delete button.dataset.oldText}}

function tableCurrent(){if(!current)return null;const s=A.state();return current.type==='mesa'?s.tables.find(x=>x.id===current.id):s.tabs.find(x=>x.id===current.id)}
function elapsedMinutes(t){if(Number(t?.openedAt)>0)return Math.max(0,Math.floor((Date.now()-Number(t.openedAt))/60000));return Number(t?.opened||0)}
function ensureDeleteButton(){
  let b=$('deleteOrder');
  if(!b&&$('requestClose')?.parentElement){b=document.createElement('button');b.id='deleteOrder';b.type='button';b.textContent='Excluir comanda';$('requestClose').parentElement.insertBefore(b,$('requestClose'));b.onclick=cancelCurrentOrder}
  const t=tableCurrent();if(b)b.classList.toggle('hidden',!t||t.status==='free');
}
function render(){const s=A.state();$('waiterNameLabel').textContent=currentWaiter();renderTables($('searchTable').value);if(!$('overlay').classList.contains('hidden')){renderProducts();renderCart();ensureDeleteButton()}}
function setMode(next){mode=next;$('bottomTables').classList.toggle('active',mode==='all');$('bottomTabs').classList.toggle('active',mode==='tabs');renderTables($('searchTable').value)}
function renderTables(filter=''){const s=A.state(),grid=$('tableGrid'),q=String(filter||'').toLowerCase().trim();const src=mode==='tabs'?s.tabs:[...s.tables,...s.tabs];const list=src.filter(t=>!q||String(t.id).includes(q)||(t.client||'').toLowerCase().includes(q));grid.innerHTML=list.length?'':'<div class="empty-state">Nenhuma mesa ou comanda encontrada.</div>';list.forEach(t=>{const free=t.status==='free',b=document.createElement('button');b.className=`table-card ${free?'free':t.status==='wait'?'wait':'busy'}`;b.innerHTML=`<i class="corner"></i><div class="table-no">${t.type==='mesa'?'Mesa '+t.id:'Comanda #'+t.id}</div><div class="client">${free?'Livre':A.esc(t.client)}</div><div class="meta">${free?'Toque para abrir':`${elapsedMinutes(t)} min • ${A.esc(t.waiter||'Garçom')}`}</div><div class="value">${free?'':A.brl(t.total)}</div>`;b.onclick=()=>openOrder(t.type,t.id);grid.appendChild(b)})}
function fillSelect(){const s=A.state(),el=$('tableSelect'),t=tableCurrent();el.innerHTML='';if(individual){el.innerHTML='<option>Comanda individual</option>';el.disabled=true;return}const available=s.tables.filter(x=>x.status==='free'||x.id===t?.id);if(!available.length){el.innerHTML='<option value="">Nenhuma mesa livre</option>';el.disabled=true;return}available.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`Mesa ${x.id}${x.status!=='free'?' • '+x.client:''}`;el.appendChild(o)});el.disabled=false}
function openOrder(type=null,id=null,newMode='mesa'){individual=newMode==='comanda'||type==='comanda';current=type&&id?{type,id}:null;cart={};const t=tableCurrent();if(!t&&!individual&&!A.state().tables.some(x=>x.status==='free'))return A.toast('Não há mesa livre no momento');$('sheetTitle').textContent=t?(t.type==='mesa'?`Mesa ${t.id} • ${t.client||'Livre'}`:`Comanda #${t.id} • ${t.client}`):(individual?'Nova comanda individual':'Abrir mesa');$('clientName').value=t?.client||'';fillSelect();if(t?.type==='mesa')$('tableSelect').value=t.id;$('requestClose').classList.toggle('hidden',!t||t.status==='wait');ensureDeleteButton();renderProducts();renderCart();$('overlay').classList.remove('hidden')}
function renderProducts(){const s=A.state(),active=s.products.filter(p=>p.active!==false),cats=s.categories.filter(c=>active.some(p=>p.cat===c));if(!cats.includes(cat))cat=cats[0]||'';$('categoryChips').innerHTML=cats.map(c=>`<button class="chip ${c===cat?'active':''}" data-cat="${encodeURIComponent(c)}">${A.icons[c]||'●'} ${A.esc(c)}</button>`).join('');document.querySelectorAll('#categoryChips [data-cat]').forEach(b=>b.onclick=()=>{cat=decodeURIComponent(b.dataset.cat);renderProducts()});const list=active.filter(p=>p.cat===cat);$('productsGrid').innerHTML=list.length?list.map(p=>`<div class="product"><div class="photo">${A.media(p)}</div><div class="pname">${A.esc(p.name)}</div><div class="pstock">${p.stock>0?'Estoque: '+p.stock:'SEM ESTOQUE'}</div><div class="prow"><span class="price">${A.brl(p.price)}</span><button class="add" data-add="${p.id}" ${p.stock-(cart[p.id]||0)<=0?'disabled':''}>+</button></div></div>`).join(''):'<div class="empty-state">Nenhum produto nesta categoria.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addProd(Number(b.dataset.add)))}
function addProd(id){if(saving)return;const p=A.product(id);if(!p||p.stock-(cart[id]||0)<=0)return A.toast('Produto sem estoque');cart[id]=(cart[id]||0)+1;renderProducts();renderCart()}
function removeProd(id){if(saving||!cart[id])return;cart[id]--;if(cart[id]<=0)delete cart[id];renderProducts();renderCart()}
function fmtTime(ts){if(!ts)return'horário antigo não registrado';return new Date(Number(ts)).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'})}
function historyArray(s){if(!Array.isArray(s.itemHistory))s.itemHistory=[];return s.itemHistory}
function ensureLineIdentity(item){if(!item.lineId)item.lineId=`legacy-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;return item.lineId}
function syncHistory(s,t,item,prod,actor,extra={}){const hist=historyArray(s),lineId=ensureLineIdentity(item);let h=hist.find(x=>x.lineId===lineId);if(!h){h={lineId,pid:item.pid,qty:Number(item.qty||0),name:prod?.name||`Produto ${item.pid}`,price:Number(item.price??prod?.price??0),waiter:item.waiter||actor,username:item.username||currentUsername(),launchedAt:Number(item.launchedAt)||0,orderType:t.type,orderId:t.id,client:t.client||'',legacy:!item.launchedAt};hist.push(h)}Object.assign(h,{pid:item.pid,qty:Number(item.qty||0),name:prod?.name||h.name||`Produto ${item.pid}`,price:Number(item.price??prod?.price??h.price??0),waiter:item.waiter||h.waiter||actor,username:item.username||h.username||currentUsername(),orderType:t.type,orderId:t.id,client:t.client||h.client||''},extra);return h}
function renderCart(){const entries=Object.entries(cart),existing=tableCurrent(),base=Number(existing?.total||0);let pending=0,html='';if(existing){html+=`<div class="cart-current"><span>Total já lançado</span><strong>${A.brl(base)}</strong></div>`;const items=existing.items||[];if(items.length){html+='<div class="cart-existing-title">Itens já lançados • você pode corrigir</div>';html+=items.map((i,index)=>{const p=A.product(i.pid),price=Number(i.price??p?.price??0);return`<div class="cart-line existing"><div class="cart-line-main"><span>${Number(i.qty||0)}× ${A.esc(p?.name||'Produto')}</span><small>${A.esc(i.waiter||existing.waiter||'Garçom')} • ${fmtTime(i.launchedAt)}</small></div><div class="cart-actions editing"><strong>${A.brl(price*Number(i.qty||0))}</strong><button class="order-edit-btn" data-existing-minus="${index}">−1</button><button class="order-edit-btn" data-existing-plus="${index}">+1</button><button class="order-edit-btn swap-item" data-existing-swap="${index}">Trocar</button><button class="order-edit-btn remove-item" data-existing-remove="${index}">Remover</button></div></div>`}).join('')}}if(!entries.length)html+='<div class="cart-empty">Nenhum item novo adicionado.</div>';else html+=entries.map(([id,q])=>{const p=A.product(id);if(!p)return'';pending+=p.price*q;return`<div class="cart-line"><span>${q}× ${A.esc(p.name)}</span><div class="cart-actions"><strong>${A.brl(p.price*q)}</strong><button data-remove="${p.id}">−</button><button data-plus="${p.id}">+</button></div></div>`}).join('');$('cartLines').innerHTML=html;$('cartTotal').textContent=A.brl(base+pending);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeProd(Number(b.dataset.remove)));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>addProd(Number(b.dataset.plus)));document.querySelectorAll('[data-existing-minus]').forEach(b=>b.onclick=()=>changeExistingQty(Number(b.dataset.existingMinus),-1));document.querySelectorAll('[data-existing-plus]').forEach(b=>b.onclick=()=>changeExistingQty(Number(b.dataset.existingPlus),1));document.querySelectorAll('[data-existing-swap]').forEach(b=>b.onclick=()=>swapExisting(Number(b.dataset.existingSwap)));document.querySelectorAll('[data-existing-remove]').forEach(b=>b.onclick=()=>removeExisting(Number(b.dataset.existingRemove)))}
async function changeExistingQty(index,delta){if(saving)return;const before=tableCurrent(),item=before?.items?.[index],p=item?A.product(item.pid):null;if(!before||!item||!p)return;if(delta>0&&Number(p.stock||0)<delta)return A.toast('Estoque insuficiente para aumentar a quantidade.');const actor=currentWaiter(),editedAt=Date.now();saving=true;try{const ok=await A.commit(s=>{const t=current.type==='mesa'?s.tables.find(x=>x.id===current.id):s.tabs.find(x=>x.id===current.id),i=t?.items?.[index];if(!t||!i)return;const prod=s.products.find(x=>x.id===i.pid);if(!prod)return;const oldQty=Number(i.qty||0),newQty=Math.max(0,oldQty+delta),diff=newQty-oldQty;if(diff>0&&Number(prod.stock||0)<diff)throw new Error('Estoque insuficiente');prod.stock=Number(prod.stock||0)-diff;t.total=Math.max(0,Number(t.total||0)+Number(prod.price||0)*diff);i.price=Number(prod.price||0);i.editedAt=editedAt;i.editedBy=actor;if(newQty<=0){i.qty=0;syncHistory(s,t,i,prod,actor,{qty:0,removed:true,editedAt,editedBy:actor});t.items.splice(index,1)}else{i.qty=newQty;syncHistory(s,t,i,prod,actor,{removed:false,editedAt,editedBy:actor})}},`Pedido corrigido por ${actor}`);if(ok){renderProducts();renderCart()}}finally{saving=false}}
async function removeExisting(index){const t=tableCurrent(),i=t?.items?.[index],p=i?A.product(i.pid):null;if(!t||!i||!p)return;if(!confirm(`Remover ${i.qty}× ${p.name} deste pedido?`))return;await changeExistingQty(index,-Number(i.qty||0))}
async function swapExisting(index){if(saving)return;const t=tableCurrent(),item=t?.items?.[index],oldP=item?A.product(item.pid):null;if(!t||!item||!oldP)return;const q=prompt(`Trocar ${item.qty}× ${oldP.name}.\nDigite o nome ou ID do produto correto:`,'');if(!q?.trim())return;const query=q.trim().toLowerCase(),next=A.state().products.find(p=>String(p.id)===q.trim()||p.name.toLowerCase()===query)||A.state().products.find(p=>p.name.toLowerCase().includes(query));if(!next)return A.toast('Produto não encontrado.');if(next.id===oldP.id)return A.toast('Esse já é o produto lançado.');if(Number(next.stock||0)<Number(item.qty||0))return A.toast('Estoque insuficiente do produto correto.');const actor=currentWaiter(),editedAt=Date.now();saving=true;try{const ok=await A.commit(s=>{const order=current.type==='mesa'?s.tables.find(x=>x.id===current.id):s.tabs.find(x=>x.id===current.id),it=order?.items?.[index];if(!order||!it)return;const oldProd=s.products.find(x=>x.id===it.pid),newProd=s.products.find(x=>x.id===next.id);if(!oldProd||!newProd)return;const qty=Number(it.qty||0);if(Number(newProd.stock||0)<qty)throw new Error('Estoque insuficiente');oldProd.stock=Number(oldProd.stock||0)+qty;newProd.stock=Number(newProd.stock||0)-qty;order.total=Math.max(0,Number(order.total||0)+(Number(newProd.price||0)-Number(oldProd.price||0))*qty);it.pid=newProd.id;it.price=Number(newProd.price||0);it.editedAt=editedAt;it.editedBy=actor;syncHistory(s,order,it,newProd,actor,{removed:false,editedAt,editedBy:actor})},`Produto corrigido por ${actor}`);if(ok){renderProducts();renderCart()}}finally{saving=false}}
async function confirmOrder(){
  if(saving)return;
  const name=$('clientName').value.trim(),entries=Object.entries(cart),selected=Number($('tableSelect').value),existing=tableCurrent(),waiterName=currentWaiter();
  if(!name)return A.toast('Informe o nome do cliente');if(!entries.length)return A.toast(existing?'Adicione um novo item para lançar':'Adicione pelo menos um produto');if(!existing&&!individual&&!selected)return A.toast('Nenhuma mesa livre disponível');
  for(const[id,q]of entries){const p=A.product(id);if(!p||Number(p.stock)<Number(q))return A.toast(`Estoque insuficiente: ${p?.name||'produto'}`)}
  const orderType=existing?.type||(individual?'comanda':'mesa'),orderId=existing?.id||(individual?null:selected),items=entries.map(([id,q])=>({pid:Number(id),qty:Number(q)}));
  const key=JSON.stringify({orderType,orderId,name,items}),requestId=pendingLaunchId(key),btn=$('confirmOrder');
  saving=true;setBusy(btn,true,'Lançando...');
  try{
    const r=await waiterRpc('waiter_launch_items',{p_order_type:orderType,p_order_id:orderId,p_client:name,p_items:items,p_request_id:requestId});
    if(!r?.success){A.toast(r?.error||'Não foi possível lançar o pedido.');return}
    applyStocks(r.stock_updates);applyOrder(orderType,r.order_id,r.order_data);clearPendingLaunch();
    $('overlay').classList.add('hidden');current=null;cart={};A.toast(`Pedido lançado por ${waiterName}`);render();
  }catch(e){console.error('Falha no lançamento rápido',e);const m=String(e?.message||'').toLowerCase();if(m.includes('sessão'))A.toast('Sessão encerrada. Entre novamente.');else if(e?.name==='AbortError')A.toast('Servidor demorou a responder. Tente novamente; o sistema não duplicará o pedido.');else A.toast('Não foi possível lançar agora. Tente novamente.');}
  finally{saving=false;setBusy(btn,false);}
}
async function requestClose(){if(saving)return;const t=tableCurrent();if(!t)return;const btn=$('requestClose');saving=true;setBusy(btn,true,'Solicitando...');try{const r=await waiterRpc('waiter_request_close_fast',{p_order_type:t.type,p_order_id:t.id});if(!r?.success){A.toast(r?.error||'Não foi possível solicitar o fechamento.');return}applyOrder(t.type,t.id,r.order_data);A.toast('Fechamento solicitado ao caixa');$('overlay').classList.add('hidden');current=null;render()}catch(e){console.error(e);A.toast('Não foi possível solicitar o fechamento.')}finally{saving=false;setBusy(btn,false)}}
async function cancelCurrentOrder(){if(saving)return;const t=tableCurrent();if(!t||t.status==='free')return;const label=t.type==='mesa'?`Mesa ${t.id}`:`Comanda #${t.id}`;if(!confirm(`Excluir a comanda da ${label}?\n\nTodos os itens serão removidos e devolvidos ao estoque. Essa ação NÃO registra venda.`))return;const btn=$('deleteOrder');saving=true;setBusy(btn,true,'Excluindo...');try{const r=await waiterRpc('waiter_cancel_order',{p_order_type:t.type,p_order_id:t.id});if(!r?.success){A.toast(r?.error||'Não foi possível excluir a comanda.');return}applyStocks(r.stock_updates);const s=A.state();if(t.type==='mesa'){const i=s.tables.findIndex(x=>Number(x.id)===Number(t.id));if(i>=0)s.tables[i]={id:t.id,type:'mesa',client:'',status:'free',opened:0,total:0,items:[],waiter:currentWaiter()}}else{s.tabs=s.tabs.filter(x=>Number(x.id)!==Number(t.id))}$('overlay').classList.add('hidden');current=null;cart={};A.toast('Comanda excluída • itens devolvidos ao estoque');render()}catch(e){console.error(e);A.toast('Não foi possível excluir a comanda.')}finally{saving=false;setBusy(btn,false)}}
$('closeSheet').onclick=()=>$('overlay').classList.add('hidden');$('newTable').onclick=()=>openOrder(null,null,'mesa');$('newTab').onclick=()=>openOrder(null,null,'comanda');$('confirmOrder').onclick=confirmOrder;$('requestClose').onclick=requestClose;$('searchBtn').onclick=()=>renderTables($('searchTable').value);$('searchTable').addEventListener('input',e=>renderTables(e.target.value));$('bottomSearch').onclick=()=>{$('searchTable').focus();window.scrollTo({top:120,behavior:'smooth'})};$('bottomTables').onclick=()=>{mode='all';$('searchTable').value='';setMode('all');window.scrollTo({top:0,behavior:'smooth'})};$('bottomTabs').onclick=()=>{mode='tabs';$('searchTable').value='';setMode('tabs');window.scrollTo({top:0,behavior:'smooth'})};
window.renderPage=render;A.init();
})();