(()=>{
const A=window.APP,$=id=>document.getElementById(id);
let current=null,cart={},cat='',individual=false,mode='all';
const currentWaiter=()=>A.waiterUser()?.displayName||A.state().settings.waiterName||'Garçom';
function tableCurrent(){if(!current)return null;const s=A.state();return current.type==='mesa'?s.tables.find(x=>x.id===current.id):s.tabs.find(x=>x.id===current.id)}
function render(){const s=A.state();$('waiterNameLabel').textContent=currentWaiter();renderTables($('searchTable').value);if(!$('overlay').classList.contains('hidden')){renderProducts();renderCart()}}
function setMode(next){mode=next;$('bottomTables').classList.toggle('active',mode==='all');$('bottomTabs').classList.toggle('active',mode==='tabs');renderTables($('searchTable').value)}
function renderTables(filter=''){const s=A.state(),grid=$('tableGrid'),q=String(filter||'').toLowerCase().trim();const src=mode==='tabs'?s.tabs:[...s.tables,...s.tabs];const list=src.filter(t=>!q||String(t.id).includes(q)||(t.client||'').toLowerCase().includes(q));grid.innerHTML=list.length?'':'<div class="empty-state">Nenhuma mesa ou comanda encontrada.</div>';list.forEach(t=>{const free=t.status==='free',b=document.createElement('button');b.className=`table-card ${free?'free':t.status==='wait'?'wait':'busy'}`;b.innerHTML=`<i class="corner"></i><div class="table-no">${t.type==='mesa'?'Mesa '+t.id:'Comanda #'+t.id}</div><div class="client">${free?'Livre':A.esc(t.client)}</div><div class="meta">${free?'Toque para abrir':`${t.opened||0} min • ${A.esc(t.waiter||'Garçom')}`}</div><div class="value">${free?'':A.brl(t.total)}</div>`;b.onclick=()=>openOrder(t.type,t.id);grid.appendChild(b)})}
function fillSelect(){const s=A.state(),el=$('tableSelect'),t=tableCurrent();el.innerHTML='';if(individual){el.innerHTML='<option>Comanda individual</option>';el.disabled=true;return}const available=s.tables.filter(x=>x.status==='free'||x.id===t?.id);if(!available.length){el.innerHTML='<option value="">Nenhuma mesa livre</option>';el.disabled=true;return}available.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`Mesa ${x.id}${x.status!=='free'?' • '+x.client:''}`;el.appendChild(o)});el.disabled=false}
function openOrder(type=null,id=null,newMode='mesa'){individual=newMode==='comanda'||type==='comanda';current=type&&id?{type,id}:null;cart={};const t=tableCurrent();if(!t&&!individual&&!A.state().tables.some(x=>x.status==='free'))return A.toast('Não há mesa livre no momento');$('sheetTitle').textContent=t?(t.type==='mesa'?`Mesa ${t.id} • ${t.client||'Livre'}`:`Comanda #${t.id} • ${t.client}`):(individual?'Nova comanda individual':'Abrir mesa');$('clientName').value=t?.client||'';fillSelect();if(t?.type==='mesa')$('tableSelect').value=t.id;$('requestClose').classList.toggle('hidden',!t||t.status==='wait');renderProducts();renderCart();$('overlay').classList.remove('hidden')}
function renderProducts(){const s=A.state(),active=s.products.filter(p=>p.active!==false),cats=s.categories.filter(c=>active.some(p=>p.cat===c));if(!cats.includes(cat))cat=cats[0]||'';$('categoryChips').innerHTML=cats.map(c=>`<button class="chip ${c===cat?'active':''}" data-cat="${encodeURIComponent(c)}">${A.icons[c]||'●'} ${A.esc(c)}</button>`).join('');document.querySelectorAll('#categoryChips [data-cat]').forEach(b=>b.onclick=()=>{cat=decodeURIComponent(b.dataset.cat);renderProducts()});const list=active.filter(p=>p.cat===cat);$('productsGrid').innerHTML=list.length?list.map(p=>`<div class="product"><div class="photo">${A.media(p)}</div><div class="pname">${A.esc(p.name)}</div><div class="pstock">${p.stock>0?'Estoque: '+p.stock:'SEM ESTOQUE'}</div><div class="prow"><span class="price">${A.brl(p.price)}</span><button class="add" data-add="${p.id}" ${p.stock-(cart[p.id]||0)<=0?'disabled':''}>+</button></div></div>`).join(''):'<div class="empty-state">Nenhum produto nesta categoria.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addProd(Number(b.dataset.add)))}
function addProd(id){const p=A.product(id);if(!p||p.stock-(cart[id]||0)<=0)return A.toast('Produto sem estoque');cart[id]=(cart[id]||0)+1;renderProducts();renderCart()}
function removeProd(id){if(!cart[id])return;cart[id]--;if(cart[id]<=0)delete cart[id];renderProducts();renderCart()}
function renderCart(){const entries=Object.entries(cart),existing=tableCurrent(),base=Number(existing?.total||0);let pending=0;let html=existing?`<div class="cart-current"><span>Total já lançado</span><strong>${A.brl(base)}</strong></div>`:'';if(!entries.length)html+='<div class="cart-empty">Nenhum item novo adicionado.</div>';else html+=entries.map(([id,q])=>{const p=A.product(id);if(!p)return'';pending+=p.price*q;return`<div class="cart-line"><span>${q}× ${A.esc(p.name)}</span><div class="cart-actions"><strong>${A.brl(p.price*q)}</strong><button data-remove="${p.id}">−</button><button data-plus="${p.id}">+</button></div></div>`}).join('');$('cartLines').innerHTML=html;$('cartTotal').textContent=A.brl(base+pending);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeProd(Number(b.dataset.remove)));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>addProd(Number(b.dataset.plus)))}
async function confirmOrder(){const name=$('clientName').value.trim(),entries=Object.entries(cart),selected=Number($('tableSelect').value),existing=tableCurrent(),waiterName=currentWaiter();if(!name)return A.toast('Informe o nome do cliente');if(!entries.length)return A.toast(existing?'Adicione um novo item para lançar':'Adicione pelo menos um produto');if(!existing&&!individual&&!selected)return A.toast('Nenhuma mesa livre disponível');for(const[id,q]of entries){const p=A.product(id);if(!p||p.stock<q)return A.toast(`Estoque insuficiente: ${p?.name||'produto'}`)}const ok=await A.commit(st=>{let t;if(current)t=current.type==='mesa'?st.tables.find(x=>x.id===current.id):st.tabs.find(x=>x.id===current.id);if(!t){if(individual){const next=Math.max(100,...st.tabs.map(x=>x.id))+1;t={id:next,type:'comanda',client:name,status:'busy',opened:0,total:0,items:[],waiter:waiterName};st.tabs.push(t)}else{t=st.tables.find(x=>x.id===selected);if(!t||t.status!=='free')throw new Error('Mesa indisponível');t.client=name;t.status='busy';t.waiter=waiterName}}entries.forEach(([id,q])=>{const p=st.products.find(x=>x.id===Number(id));p.stock-=Number(q);t.total=Number(t.total||0)+p.price*Number(q);const old=t.items.find(i=>i.pid===Number(id)&&(i.waiter||t.waiter)===waiterName);old?old.qty+=Number(q):t.items.push({pid:Number(id),qty:Number(q),waiter:waiterName})});t.client=name;t.waiter=waiterName;if(t.status==='free')t.status='busy'},`Pedido lançado por ${waiterName}`);if(ok){$('overlay').classList.add('hidden');current=null;cart={}}}
async function requestClose(){const t=tableCurrent();if(!t)return;const ok=await A.commit(st=>{const x=t.type==='mesa'?st.tables.find(y=>y.id===t.id):st.tabs.find(y=>y.id===t.id);if(x)x.status='wait'},'Fechamento solicitado ao caixa');if(ok){$('overlay').classList.add('hidden');current=null}}
$('closeSheet').onclick=()=>$('overlay').classList.add('hidden');$('newTable').onclick=()=>openOrder(null,null,'mesa');$('newTab').onclick=()=>openOrder(null,null,'comanda');$('confirmOrder').onclick=confirmOrder;$('requestClose').onclick=requestClose;$('searchBtn').onclick=()=>renderTables($('searchTable').value);$('searchTable').addEventListener('input',e=>renderTables(e.target.value));$('bottomSearch').onclick=()=>{$('searchTable').focus();window.scrollTo({top:120,behavior:'smooth'})};$('bottomTables').onclick=()=>{mode='all';$('searchTable').value='';setMode('all');window.scrollTo({top:0,behavior:'smooth'})};$('bottomTabs').onclick=()=>{mode='tabs';$('searchTable').value='';setMode('tabs');window.scrollTo({top:0,behavior:'smooth'})};
window.renderPage=render;A.init();
})();
