(()=>{
const A=window.APP;if(!A||document.body.dataset.page!=='waiter'||window.__waiterUiV28)return;window.__waiterUiV28=true;
const SUPABASE_URL='https://dsipffnmerbowaddbcxe.supabase.co',SUPABASE_KEY='sb_publishable_vI64CItP0mGD4HD2DFJ2zw_zyZaveCz',SESSION_KEY='comandaPrimeWaiterSessionV1';
const $=s=>document.querySelector(s);const token=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')?.token||''}catch(_){return''}};
async function rpc(name,body={}){const t=token();if(!t)throw new Error('Sessão encerrada. Entre novamente.');const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({p_session_token:t,...body}),cache:'no-store'});const d=await r.json().catch(()=>null),x=Array.isArray(d)?d[0]:d;if(!r.ok)throw new Error(x?.message||x?.error||`Erro ${r.status}`);return x;}
const style=document.createElement('style');style.textContent=`
#waiterView .search,#waiterView .action-row,#bottomSearch{display:none!important}.bottom-nav{grid-template-columns:1fr 1fr!important}.waiter-adjustments{display:none}.waiter-adjustments.active{display:block}.waiter-adjust-card{background:#fff;border:1px solid #e5e8ef;border-radius:16px;padding:14px;margin:10px 0;box-shadow:0 5px 18px rgba(10,22,50,.05)}.waiter-adjust-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.waiter-adjust-head strong{color:#0b1739}.waiter-adjust-head span,.waiter-adjust-items{font-size:11px;color:#747d92}.waiter-adjust-items{margin-top:10px;line-height:1.55}.waiter-reopen{margin-top:12px;width:100%;border:0;border-radius:12px;padding:12px;background:#0b1739;color:#fff;font-weight:900}.add-table-card{border:2px dashed #cbd2df!important;background:#f8f9fc!important;color:#0b1739!important;display:grid!important;place-items:center!important;min-height:116px}.add-table-card .table-no{font-size:30px!important}.add-table-card .client{font-weight:900!important}.cart #deleteOrder{display:block!important;width:auto!important;align-self:flex-start!important;border:0!important;border-radius:14px!important;padding:13px 18px!important;margin-top:10px!important;background:#fff0f0!important;color:#a60f17!important;font-weight:950!important;box-shadow:none!important}.waiter-pay-v28{position:fixed;inset:0;z-index:10050;background:rgba(5,12,32,.68);display:grid;place-items:end center;padding:12px}.waiter-pay-v28.hidden{display:none}.waiter-pay-sheet-v28{width:min(520px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px 24px 18px 18px;padding:18px}.pay-head-v28{display:flex;justify-content:space-between;align-items:center}.pay-head-v28 button{border:0;border-radius:10px;width:38px;height:38px}.pay-items-v28{margin:12px 0;border:1px solid #e7eaf0;border-radius:14px;overflow:hidden}.pay-line-v28{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px 12px;border-bottom:1px solid #eef0f4}.pay-line-v28:last-child{border-bottom:0}.pay-line-v28 small{display:block;color:#7d8496;margin-top:2px}.pay-total-v28{display:flex;justify-content:space-between;font-size:19px;font-weight:950;margin:12px 0}.pay-methods-v28{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pay-method-v28{border:2px solid #e5e8ef;border-radius:13px;padding:12px;background:#fff;font-weight:900}.pay-method-v28.active{border-color:#b51019;background:#fff2f2;color:#9c1119}.split-v28{margin:12px 0;padding:12px;background:#f6f7fa;border-radius:13px}.split-v28 input{width:70px;padding:8px;border:1px solid #d9dde6;border-radius:8px}.split-value-v28{font-weight:950;margin-left:8px}.finish-v28{width:100%;border:0;border-radius:14px;padding:14px;margin-top:12px;background:#b51019;color:#fff;font-weight:950}.finish-v28:disabled{opacity:.5}
`;document.head.appendChild(style);
const content=$('#waiterView .content'),legend=$('#waiterView .legend'),grid=$('#tableGrid'),title=$('.screen-title'),bottomTables=$('#bottomTables'),bottomTabs=$('#bottomTabs');
if(bottomTabs)bottomTabs.innerHTML='⚙<br>Ajustes';
const panel=document.createElement('div');panel.id='waiterAdjustments';panel.className='waiter-adjustments';grid?.after(panel);
function fmt(ts){if(!ts)return'Horário não registrado';return new Date(Number(ts)).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function showTables(){panel.classList.remove('active');grid.style.display='grid';if(legend)legend.style.display='flex';if(title)title.textContent='Mesas';bottomTables?.classList.add('active');bottomTabs?.classList.remove('active');decorateGrid()}
function showAdjustments(){grid.style.display='none';if(legend)legend.style.display='none';panel.classList.add('active');if(title)title.textContent='Ajustes';bottomTables?.classList.remove('active');bottomTabs?.classList.add('active');renderAdjustments()}
if(bottomTables)bottomTables.onclick=showTables;if(bottomTabs)bottomTabs.onclick=showAdjustments;
function decorateGrid(){if(!grid||panel.classList.contains('active'))return;[...grid.querySelectorAll('.table-card')].forEach(b=>{const n=b.querySelector('.table-no')?.textContent||'';if(/^Comanda/i.test(n))b.remove()});if(grid.querySelector('.add-table-card'))return;const b=document.createElement('button');b.className='table-card add-table-card';b.innerHTML='<div class="table-no">＋</div><div class="client">Adicionar mesa</div><div class="meta">Cria a próxima mesa</div>';b.onclick=addTable;grid.appendChild(b)}
async function addTable(){if(A.state()?.cash?.status!=='open')return A.toast('Abra o caixa antes de adicionar mesa.');try{const r=await rpc('waiter_add_table');if(!r?.success)throw new Error(r?.error||'Não foi possível criar a mesa.');A.state().tables.push(r.table_data);window.renderPage?.();A.toast(`Mesa ${r.table_id} criada`)}catch(e){console.error(e);A.toast(e.message||'Não foi possível criar a mesa.')}}
function allClosed(){return [...(A.state().closedSales||[]).map(x=>({...x,_kind:'closed'})),...(A.state().unpaidSales||[]).map(x=>({...x,_kind:'unpaid'}))].sort((a,b)=>Number(b.closedAt||b.unpaidAt||0)-Number(a.closedAt||a.unpaidAt||0))}
function renderAdjustments(){const list=allClosed();panel.innerHTML=list.length?list.map(s=>`<div class="waiter-adjust-card"><div class="waiter-adjust-head"><div><strong>${s.type==='mesa'?'Mesa '+s.refId:'Comanda #'+s.refId} • ${A.esc(s.client||'Cliente')}</strong><span>${fmt(s.closedAt||s.unpaidAt)} • ${A.esc(s.closedBy||s.recordedBy||s.waiter||'Garçom')}</span></div><strong>${A.brl(s.total)}</strong></div><div class="waiter-adjust-items">${(s.items||[]).map(i=>`${Number(i.qty||0)}× ${A.esc(i.name||A.product(i.pid)?.name||'Produto')} • ${A.brl(Number(i.price||0)*Number(i.qty||0))}`).join('<br>')}</div><button class="waiter-reopen" data-reopen="${s.id}">Reabrir para ajustar</button></div>`).join(''):'<div class="empty-state">Nenhuma conta fechada para ajustar.</div>';panel.querySelectorAll('[data-reopen]').forEach(b=>b.onclick=()=>reopen(Number(b.dataset.reopen)))}
async function reopen(id){const sale=allClosed().find(x=>Number(x.id)===id);if(!sale)return;if(!confirm(`Reabrir ${sale.type==='mesa'?'Mesa '+sale.refId:'Comanda #'+sale.refId} de ${sale.client||'cliente'}?`))return;try{await rpc('waiter_archive_sale',{p_sale_id:id});const r=await rpc('waiter_reopen_sale',{p_sale_id:id});if(!r?.success)throw new Error(r?.error||'Não foi possível reabrir.');const normalized=await rpc('waiter_normalize_order_lines',{p_order_type:r.order_type,p_order_id:r.order_id});const s=A.state();s.closedSales=(s.closedSales||[]).filter(x=>Number(x.id)!==id);s.unpaidSales=(s.unpaidSales||[]).filter(x=>Number(x.id)!==id);if(r.order_type==='mesa'){const i=s.tables.findIndex(x=>Number(x.id)===Number(r.order_id));if(i>=0)s.tables[i]=normalized||r.order_data}else{s.tabs=s.tabs||[];s.tabs.push(normalized||r.order_data)}window.renderPage?.();showTables();A.toast('Conta reaberta • alterações ficarão registradas no Admin');setTimeout(()=>{[...grid.querySelectorAll('.table-card')].find(b=>(b.querySelector('.table-no')?.textContent||'').includes(`${r.order_type==='mesa'?'Mesa':'Comanda #'} ${r.order_id}`))?.click()},120)}catch(e){console.error(e);A.toast(e.message||'Não foi possível reabrir.')}}
function currentRef(){const tx=$('#sheetTitle')?.textContent||'';let m=tx.match(/^Mesa\s+(\d+)/i);if(m)return{type:'mesa',id:Number(m[1])};m=tx.match(/^Comanda\s+#(\d+)/i);if(m)return{type:'comanda',id:Number(m[1])};return null}
function currentOrder(ref){return ref?.type==='mesa'?A.state().tables.find(x=>Number(x.id)===ref.id):(A.state().tabs||[]).find(x=>Number(x.id)===ref?.id)}
function applyStocks(us){(us||[]).forEach(u=>{const p=A.state().products.find(x=>Number(x.id)===Number(u.pid));if(p)p.stock=Number(u.stock)})}
function applyOrder(ref,o){if(!o)return;const arr=ref.type==='mesa'?A.state().tables:A.state().tabs,i=arr.findIndex(x=>Number(x.id)===ref.id);if(i>=0)arr[i]=o}
document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-existing-minus],[data-existing-plus],[data-existing-remove],[data-existing-swap]');if(!b)return;const ref=currentRef(),o=currentOrder(ref);if(!ref||!o)return;const idx=Number(b.dataset.existingMinus??b.dataset.existingPlus??b.dataset.existingRemove??b.dataset.existingSwap),item=o.items?.[idx];if(!item?.lineId)return;e.preventDefault();e.stopImmediatePropagation();let action=b.hasAttribute('data-existing-plus')?'inc':b.hasAttribute('data-existing-minus')?'dec':b.hasAttribute('data-existing-remove')?'remove':'swap',newPid=null;if(action==='remove'&&!confirm('Remover este item da comanda?'))return;if(action==='swap'){const q=prompt('Digite o nome ou ID do novo produto:','');if(!q)return;const qq=q.trim().toLowerCase(),p=A.state().products.find(x=>String(x.id)===q.trim()||String(x.name||'').toLowerCase()===qq)||A.state().products.find(x=>String(x.name||'').toLowerCase().includes(qq));if(!p)return A.toast('Produto não encontrado.');newPid=p.id}b.disabled=true;try{const r=await rpc('waiter_adjust_order_item',{p_order_type:ref.type,p_order_id:ref.id,p_line_id:item.lineId,p_action:action,p_new_pid:newPid});if(!r?.success)throw new Error(r?.error||'Não foi possível ajustar.');applyStocks(r.stock_updates);applyOrder(ref,r.order_data);window.renderPage?.();A.toast('Comanda atualizada • alteração registrada')}catch(err){console.error(err);A.toast(err.message||'Não foi possível ajustar.')}finally{b.disabled=false}},true);
const pay=document.createElement('div');pay.id='waiterPayV28';pay.className='waiter-pay-v28 hidden';pay.innerHTML=`<div class="waiter-pay-sheet-v28"><div class="pay-head-v28"><h3>Fechar conta</h3><button type="button" id="payCloseV28">×</button></div><div id="payTitleV28"></div><div id="payItemsV28" class="pay-items-v28"></div><div class="pay-total-v28"><span>Total</span><span id="payTotalV28"></span></div><div class="split-v28"><label>Dividir conta entre <input id="splitCountV28" type="number" min="1" max="100" value="1"> pessoa(s)</label><span class="split-value-v28" id="splitValueV28"></span></div><div class="pay-methods-v28"><button class="pay-method-v28" data-pay-v28="Pix">Pix</button><button class="pay-method-v28" data-pay-v28="Dinheiro">Dinheiro</button><button class="pay-method-v28" data-pay-v28="Débito">Débito</button><button class="pay-method-v28" data-pay-v28="Crédito">Crédito</button><button class="pay-method-v28" data-pay-v28="Não pagou">Não pagou</button></div><button id="finishPayV28" class="finish-v28" disabled>Confirmar fechamento</button></div>`;document.body.appendChild(pay);
let payRef=null,payMethod='';function payOrder(){return currentOrder(payRef)}
function updateSplit(){const o=payOrder(),n=Math.max(1,Number($('#splitCountV28')?.value||1));$('#splitValueV28').textContent=o?`${A.brl(Number(o.total||0)/n)} por pessoa`:''}
function openPay(){if(A.state()?.cash?.status!=='open')return A.toast('Caixa fechado.');payRef=currentRef();const o=payOrder();if(!payRef||!o||(o.items||[]).length===0)return A.toast('Não há itens para fechar.');payMethod='';pay.querySelectorAll('[data-pay-v28]').forEach(x=>x.classList.remove('active'));$('#finishPayV28').disabled=true;$('#splitCountV28').value=1;$('#payTitleV28').innerHTML=`<strong>${payRef.type==='mesa'?'Mesa '+payRef.id:'Comanda #'+payRef.id}</strong> • ${A.esc(o.client||'Cliente')}`;$('#payItemsV28').innerHTML=(o.items||[]).map(i=>{const p=A.product(i.pid),pr=Number(i.price??p?.price??0);return`<div class="pay-line-v28"><div><strong>${Number(i.qty||0)}× ${A.esc(p?.name||'Produto')}</strong><small>${fmt(i.launchedAt)} • ${A.esc(i.waiter||o.waiter||'Garçom')}</small></div><strong>${A.brl(pr*Number(i.qty||0))}</strong></div>`}).join('');$('#payTotalV28').textContent=A.brl(o.total);updateSplit();pay.classList.remove('hidden')}
function closePay(){pay.classList.add('hidden');payRef=null;payMethod=''}
$('#payCloseV28').onclick=closePay;$('#splitCountV28').oninput=updateSplit;pay.querySelectorAll('[data-pay-v28]').forEach(b=>b.onclick=()=>{payMethod=b.dataset.payV28;pay.querySelectorAll('[data-pay-v28]').forEach(x=>x.classList.toggle('active',x===b));$('#finishPayV28').disabled=false});
$('#finishPayV28').onclick=async()=>{const o=payOrder();if(!o||!payMethod)return;const btn=$('#finishPayV28'),split=Math.max(1,Math.floor(Number($('#splitCountV28').value||1)));btn.disabled=true;btn.textContent='Fechando...';try{const r=await rpc('waiter_close_sale_detailed',{p_type:payRef.type,p_id:payRef.id,p_payment:payMethod,p_split_count:split});if(!r?.success)throw new Error(r?.error||'Não foi possível fechar.');closePay();$('#overlay')?.classList.add('hidden');A.toast(`Conta fechada em ${payMethod} • Admin atualizado`)}catch(e){console.error(e);A.toast(e.message||'Não foi possível fechar.')}finally{btn.disabled=false;btn.textContent='Confirmar fechamento'}};
document.addEventListener('click',e=>{const b=e.target.closest?.('#requestClose');if(!b||b.classList.contains('hidden'))return;e.preventDefault();e.stopImmediatePropagation();openPay()},true);
const originalRender=window.renderPage;window.renderPage=()=>{originalRender?.();setTimeout(()=>{decorateGrid();if(panel.classList.contains('active'))renderAdjustments()},0)};decorateGrid();
})();
