(()=>{
const A=window.APP,$=id=>document.getElementById(id);let current=null,cart={},cat='',individual=false;
function tableCurrent(){if(!current)return null;const s=A.state();return current.type==='mesa'?s.tables.find(x=>x.id===current.id):s.tabs.find(x=>x.id===current.id)}
function render(){const s=A.state();$('waiterNameLabel').textContent=s.settings.waiterName;renderTables($('searchTable').value);if(!$('overlay').classList.contains('hidden'))renderProducts()}
function renderTables(filter=''){const s=A.state(),grid=$('tableGrid'),q=String(filter||'').toLowerCase().trim();const list=[...s.tables,...s.tabs].filter(t=>!q||String(t.id).includes(q)||(t.client||'').toLowerCase().includes(q));grid.innerHTML=list.length?'':'<div class="empty-state">Nenhuma mesa ou comanda encontrada.</div>';list.forEach(t=>{const free=t.status==='free',b=document.createElement('button');b.className=`table-card ${free?'free':t.status==='wait'?'wait':'busy'}`;b.innerHTML=`<i class="corner"></i><div class="table-no">${t.type==='mesa'?'Mesa '+t.id:'Comanda #'+t.id}</div><div class="client">${free?'Livre':A.esc(t.client)}</div><div class="meta">${free?'Toque para abrir':`${t.opened||0} min • ${A.esc(t.waiter||s.settings.waiterName)}`}</div><div class="value">${free?'':A.brl(t.total)}</div>`;b.onclick=()=>openOrder(t.type,t.id);grid.appendChild(b)})}
function fillSelect(){const s=A.state(),el=$('tableSelect');el.innerHTML='';if(individual){el.innerHTML='<option>Comanda individual</option>';el.disabled=true}else{s.tables.forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=`Mesa ${t.id}${t.status!=='free'?' • '+t.client:''}`;el.appendChild(o)});el.disabled=false}}
function openOrder(type=null,id=null,mode='mesa'){individual=mode==='comanda'||type==='comanda';current=type&&id?{type,id}:null;cart={};const t=tableCurrent();$('sheetTitle').textContent=t?(t.type==='mesa'?`Mesa ${t.id} • ${t.client||'Livre'}`:`Comanda #${t.id} • ${t.client}`):(individual?'Nova comanda individual':'Abrir mesa');$('clientName').value=t?.client||'';fillSelect();if(t?.type==='mesa')$('tableSelect').value=t.id;$('requestClose').classList.toggle('hidden',!t||t.status==='wait');renderProducts();renderCart();$('overlay').classList.remove('hidden')}
function renderProducts(){const s=A.state(),active=s.products.filter(p=>p.active!==false),cats=s.categories.filter(c=>active.some(p=>p.cat===c));if(!cats.includes(cat))cat=cats[0]||'';$('categoryChips').innerHTML=cats.map(c=>`<button class="chip ${c===cat?'active':''}" onclick="setCat(${JSON.stringify(c)})">${A.icons[c]||'●'} ${A.esc(c)}</button>`).join('');const list=active.filter(p=>p.cat===cat);$('productsGrid').innerHTML=list.length?list.map(p=>`<div class="product"><div class="photo">${A.media(p)}</div><div class="pname">${A.esc(p.name)}</div><div class="pstock">${p.stock>0?'Estoque: '+p.stock:'SEM ESTOQUE'}</div><div class="prow"><span class="price">${A.brl(p.price)}</span><button class="add" ${p.stock<=0?'disabled':''} onclick="addProd(${p.id})">+</button></div></div>`).join(''):'<div class="empty-state">Nenhum produto nesta categoria.</div>'}
window.setCat=c=>{cat=c;renderProducts()};window.addProd=id=>{const p=A.product(id);if(!p||p.stock-(cart[id]||0)<=0)return A.toast('Produto sem estoque');cart[id]=(cart[id]||0)+1;renderCart()};window.removeProd=id=>{if(!cart[id])return;cart[id]--;if(cart[id]<=0)delete cart[id];renderCart()};
function renderCart(){const entries=Object.entries(cart);let total=0;if(!entries.length){$('cartLines').innerHTML='<div class="cart-empty">Nenhum item adicionado.</div>';$('cartTotal').textContent=A.brl(0);return}$('cartLines').innerHTML=entries.map(([id,q])=>{const p=A.product(id);if(!p)return'';total+=p.price*q;return`<div class="cart-line"><span>${q}× ${A.esc(p.name)}</span><div class="cart-actions"><strong>${A.brl(p.price*q)}</strong><button onclick="removeProd(${p.id})">−</button><button onclick="addProd(${p.id})">+</button></div></div>`}).join('');$('cartTotal').textContent=A.brl(total)}
async function confirmOrder(){const name=$('clientName').value.trim(),entries=Object.entries(cart),selected=Number($('tableSelect').value),existing=tableCurrent();if(!name)return A.toast('Informe o nome do cliente');if(!entries.length&&!existing)return A.toast('Adicione pelo menos um produto');for(const[id,q]of entries){const p=A.product(id);if(!p||p.stock<q)return A.toast(`Estoque insuficiente: ${p?.name||'produto'}`)}const ok=await A.commit(st=>{let t;if(current)t=current.type==='mesa'?st.tables.find(x=>x.id===current.id):st.tabs.find(x=>x.id===current.id);if(!t){if(individual){const next=Math.max(100,...st.tabs.map(x=>x.id))+1;t={id:next,type:'comanda',client:name,status:'busy',opened:0,total:0,items:[],waiter:st.settings.waiterName};st.tabs.push(t)}else{t=st.tables.find(x=>x.id===selected);if(!t)return;t.client=name;t.status='busy';t.waiter=st.settings.waiterName}}entries.forEach(([id,q])=>{const p=st.products.find(x=>x.id===Number(id));p.stock-=Number(q);t.total=Number(t.total||0)+p.price*Number(q);const old=t.items.find(i=>i.pid===Number(id));old?old.qty+=Number(q):t.items.push({pid:Number(id),qty:Number(q)})});t.client=name;if(t.status==='free')t.status='busy'},'Pedido lançado • administração atualizada em tempo real');if(ok){$('overlay').classList.add('hidden');current=null;cart={}}}
async function requestClose(){const t=tableCurrent();if(!t)return;const ok=await A.commit(st=>{const x=t.type==='mesa'?st.tables.find(y=>y.id===t.id):st.tabs.find(y=>y.id===t.id);if(x)x.status='wait'},'Fechamento solicitado ao caixa');if(ok)$('overlay').classList.add('hidden')}
$('closeSheet').onclick=()=>$('overlay').classList.add('hidden');$('newTable').onclick=()=>openOrder(null,null,'mesa');$('newTab').onclick=()=>openOrder(null,null,'comanda');$('confirmOrder').onclick=confirmOrder;$('requestClose').onclick=requestClose;$('searchBtn').onclick=()=>renderTables($('searchTable').value);$('searchTable').addEventListener('input',e=>renderTables(e.target.value));$('bottomSearch').onclick=()=>{$('searchTable').focus();window.scrollTo({top:120,behavior:'smooth'})};$('bottomTables').onclick=()=>{$('searchTable').value='';renderTables('');window.scrollTo({top:0,behavior:'smooth'})};$('bottomTabs').onclick=()=>{const s=A.state(),g=$('tableGrid');g.innerHTML='';if(!s.tabs.length){g.innerHTML='<div class="empty-state">Nenhuma comanda individual aberta.</div>';return}s.tabs.forEach(t=>{const b=document.createElement('button');b.className=`table-card ${t.status==='wait'?'wait':'busy'}`;b.innerHTML=`<i class="corner"></i><div class="table-no">Comanda #${t.id}</div><div class="client">${A.esc(t.client)}</div><div class="meta">${t.opened||0} min</div><div class="value">${A.brl(t.total)}</div>`;b.onclick=()=>openOrder('comanda',t.id);g.appendChild(b)})};
window.renderPage=render;A.init();
})();
